{
 "title": "Kitten Science",
 "description": "Displays metrics from the Kitten Analysts backend.",
 "tags": [
  "kitten science",
  "kittens game"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kg_resource_value,instance)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(kg_resource_value,location)"
    }
   },
   {
    "name": "client_type",
    "label": "Client Type",
    "query": {
     "query": "label_values(kg_resource_value,client_type)"
    }
   },
   { "name": "guid", "label": "guid", "query": { "query": "label_values(guid)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resets",
   "type": "stat",
   "description": "How many times the game has been reset.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label((kg_resets_total{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}), \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Paragon",
   "type": "stat",
   "description": "Current paragon count",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(kg_resource_value{name=\"paragon\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}, \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Epiphany",
   "type": "stat",
   "description": "Current epiphany amount",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(kg_resource_value{name=\"epiphany\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}, \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Unicorns Sacrificed",
   "type": "stat",
   "description": "How many unicorns have been sacrificed so far?",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(kg_unicorns_sacrificed{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}, \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Transcendence Tier",
   "type": "stat",
   "description": "Current transcendence tier",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(kg_transcendence_tier{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}, \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Leviathans Energy",
   "type": "stat",
   "description": "Current energy level of the leviathans.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(kg_race_energy{name=\"leviathans\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}, \"client_type\")",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Kittens",
   "type": "timeseries",
   "description": "How many kittens are currently alive.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"kittens\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Paragon",
   "type": "timeseries",
   "description": "How many paragons you currently have.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"paragon\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Worship",
   "type": "timeseries",
   "description": "How much worhsip have you already accumulated?",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"worship\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Epiphany",
   "type": "timeseries",
   "description": "How much epiphany have you already accumulated?",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"epiphany\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Unobtainium",
   "type": "timeseries",
   "description": "How much unobtainium is currently in stock.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"unobtainium\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Antimatter",
   "type": "timeseries",
   "description": "How much antimatter  is currently in stock.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"antimatter\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Time Crystals",
   "type": "timeseries",
   "description": "How many time crystals are currently in stock?",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"timeCrystal\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Relics",
   "type": "timeseries",
   "description": "How many relics are currently in stock?",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"relic\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Void",
   "type": "timeseries",
   "description": "How much void is currently in stock?",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"void\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Craft Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "rate(kg_crafts_total{type=\"current\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}[$__rate_interval])",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Blackcoin",
   "type": "timeseries",
   "description": "How many blackcoins are currently in stock?",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_resource_value{name=\"blackcoin\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{client_type}}"
    }
   ]
  },
  {
   "title": "Pollution",
   "type": "timeseries",
   "description": "Current pollution level on Cath.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_pollution_total{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buildings $client_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "client_type" },
  {
   "title": "Bonfire",
   "type": "timeseries",
   "description": "Buildings on the Bonfire tab.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Bonfire\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Religion: Ziggurats",
   "type": "timeseries",
   "description": "Buildings on the Religion tab.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Religion\", group=\"ziggurats\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Religion: Order of the Sun",
   "type": "timeseries",
   "description": "Buildings on the Religion tab.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Religion\", group=\"orderOfTheSun\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Religion: Cryptotheology",
   "type": "timeseries",
   "description": "Buildings on the Religion tab.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Religion\", group=\"cryptotheology\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Space",
   "type": "timeseries",
   "description": "Buildings on the Space tab.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Space\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "description": "Buildings on the Time tab.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_building_value{tab=\"Time\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Resources $client_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "client_type",
   "collapsed": true,
   "panels": [
    {
     "title": "Resources",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 414 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "kg_resource_value{craftable=\"false\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Craftables",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 414 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "kg_resource_value{craftable=\"true\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Resources Rate Reported",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 426 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "kg_resource_rate{craftable=\"false\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Craftables Rate Reported",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 426 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "kg_resource_rate{craftable=\"true\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trade $client_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "client_type",
   "collapsed": true,
   "panels": [
    {
     "title": "Embassies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2745 },
     "targets": [
      {
       "expr": "kg_embassy_level{name!=\"leviathans\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Blackcoin Price",
     "type": "timeseries",
     "description": "Current value of blackcoin.",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 2745 },
     "targets": [
      {
       "expr": "kg_crypto_price{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Leviathan Energy",
     "type": "timeseries",
     "description": "Current energy level of leviathans.",
     "gridPos": { "h": 8, "w": 7, "x": 15, "y": 2745 },
     "targets": [
      {
       "expr": "kg_race_energy{name=\"leviathans\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  },
  { "title": "Science $client_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "client_type" },
  {
   "title": "Technologies",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "kg_tech_researched{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Pollution Production",
   "type": "timeseries",
   "description": "Shows how much pollution each building produces.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_pollution_production{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kg_pollution_total{instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Performance $client_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "repeat": "client_type",
   "collapsed": true,
   "panels": [
    {
     "title": "KS Iteration p99 Details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11999 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by(le, manager) (rate(ks_iterate_duration_bucket{manager!=\"all\", instance=~\"$instance\", location=~\"$location\", client_type=~\"$client_type\", guid=~\"$guid\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}