version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Containerfile
    ports:
      # KGNet Interface
      - "7780:7780/tcp"
      # Kittens Game Browser UI
      - "9080:8080/tcp"
      # Prometheus Exporter
      - "9091:9091/tcp"
      # Kitten Analysts Websocket
      - "9093:9093"
    volumes:
      - type: bind
        source: ./examples
        target: /local_storage
        read_only: false
      - type: bind
        source: ./output
        target: /opt/output
        read_only: true

  # Actual Kittens Game instance
  game:
    build:
      context: .
      dockerfile: game.Containerfile
    network_mode: service:backend
    volumes:
      - type: bind
        source: ./output
        target: /kittensgame/kitten-analysts
        read_only: true
      #- type: bind
      #  source: ./packages/kitten-engineers/output
      #  target: /kittensgame/kitten-engineers
      #  read_only: true
      - type: bind
        source: ./node_modules/@kitten-science/kitten-scientists/output
        target: /kittensgame/kitten-scientists
        read_only: true

  # Headless container
  #ui:
  #  build:
  #    context: .
  #    dockerfile: ui.Containerfile
  #  network_mode: service:backend
  #  volumes:
  #    - type: bind
  #      source: ./examples
  #      target: /local_storage
  #      read_only: false
